### PR TITLE
feat: docs- + deps-update

### PR DESCRIPTION
**Pull request by vobu**
this PR contains both updates to the docs (`README.md`) and updates dependencies.

## docs
`zeebe` v8 returns slightly different vars on bpmn instance creation and passes slightly different vars into the worker.  
Both is expressed as sample job creation `json` and sample worker vars.

## deps
various updates to packages, including some TS fiddling to get things right™. 
Both `got` and `chalk` are pinned to versions compatible with TS (CJS vs ESM).

### CODE REVIEW

**Comment by vobu** [comment]
this still needs some work - will get to it some time next week

**Comment by jwulf** [comment]
Hi @vobu, thank you for this!

The PR is still in draft - is it ready for review / merging yet? Anything left to do?

Josh

**Comment by vobu** [comment]
hi @jwulf, PR still needs work, specifically on the updated XML parser package → so "draft" is appropriate. 
Given that I'm OOO for the next 2 weeks, nothing much will happen until August.
But given that we use and need your package in a project (to go live in Jan '23), the PR will be worked on and finished 😄 
I'll drop a line and set the PR to "ready for review" once it is so 😆

**Comment by vobu** [comment]
so, turns out that in the meantime the respective type definition and documentation was already updated → closing this PR.
But @jwulf - does it still make sense to look at bumping deps to their latest cjs version (e.g. `got`) or their most current one (such as commitizen)? If so, I'll open a new PR with the dep bumps.

**Pull request closed without merging**
