### PR TITLE
fix: pin `@grpc` dependencies to stable version

### PR DESCRIPTION
**Pull request by nikku**
Related to https://github.com/camunda-community-hub/zeebe-client-node-js/issues/288
Related to https://github.com/barmac/zeebe-tls-connection-test/issues/1

Closes https://github.com/camunda-community-hub/zeebe-client-node-js/issues/290

### CODE REVIEW

**Comment by nikku** [comment]
Do we do actual integration tests against Zeebe self-managed? If so we could consider to execute these continuously to figure if future dependency upgrade break the system again.

**Comment by jwulf** [comment]
> Do we do actual integration tests against Zeebe self-managed? If so we could consider to execute these continuously to figure if future dependency upgrade break the system again.

I have a test that runs locally before commit against a local insecure broker. Then there is a CI test against an insecure broker. 

Let's pin the deps so that they don't move unpredictably.

**Comment by nikku** [comment]
We have built a test bed including [CI workflow](https://github.com/camunda/zeebe-connection-test/blob/main/.github/workflows/CI.yml) to verify `zeebe-node` interaction with a secured server. Maybe that is worth incorporating here.

**Comment by jwulf** [comment]
Thanks for this. I pinned them to a later version.

**Pull request closed without merging**
